name: Release And Update
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Release APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
      
      - name: Create Release and Upload debug APK
        uses: underwindfall/create-release-with-debugapk@v1.2.4
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v3.0
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Palmrest.apk
          asset_content_type: application/zip

      - name: Release build
        run: ./gradlew assembleRelease
